// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVldOSnBya77NtJLKgdf1LkgyBz_I8aqs',
    appId: '1:163154454616:web:59467bfffee741e270c22d',
    messagingSenderId: '163154454616',
    projectId: 'mobilprogramlamafinal-548e7',
    authDomain: 'mobilprogramlamafinal-548e7.firebaseapp.com',
    storageBucket: 'mobilprogramlamafinal-548e7.appspot.com',
    measurementId: 'G-P0X4J49RHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-BS4N-Dmv5olej3spBlf4PVD8pn99b4',
    appId: '1:163154454616:android:a07799bb2e46786e70c22d',
    messagingSenderId: '163154454616',
    projectId: 'mobilprogramlamafinal-548e7',
    storageBucket: 'mobilprogramlamafinal-548e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJm03fddCBbVrU1QiUwYylVzYWkGGAkQ',
    appId: '1:163154454616:ios:603c94c33c6149e770c22d',
    messagingSenderId: '163154454616',
    projectId: 'mobilprogramlamafinal-548e7',
    storageBucket: 'mobilprogramlamafinal-548e7.appspot.com',
    iosBundleId: 'com.example.mobilprojem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJm03fddCBbVrU1QiUwYylVzYWkGGAkQ',
    appId: '1:163154454616:ios:603c94c33c6149e770c22d',
    messagingSenderId: '163154454616',
    projectId: 'mobilprogramlamafinal-548e7',
    storageBucket: 'mobilprogramlamafinal-548e7.appspot.com',
    iosBundleId: 'com.example.mobilprojem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVldOSnBya77NtJLKgdf1LkgyBz_I8aqs',
    appId: '1:163154454616:web:0a2463f275e5a53a70c22d',
    messagingSenderId: '163154454616',
    projectId: 'mobilprogramlamafinal-548e7',
    authDomain: 'mobilprogramlamafinal-548e7.firebaseapp.com',
    storageBucket: 'mobilprogramlamafinal-548e7.appspot.com',
    measurementId: 'G-VEDHXLZPZ1',
  );
}
